### ISSUE TITLE
Add CUDA 12.3

### ISSUE THREAD

**Issue by shermansiu** [conda-forge/cuda-version-feedstock#12]
### Comment:

[CUDA 12.3](https://developer.nvidia.com/cuda-downloads) was released a month ago. It would be nice to add it to [the CUDA version list](https://github.com/conda-forge/cuda-version-feedstock/blob/286f34f62fe01701fdd5c38ed51da1341853b5b9/recipe/conda_build_config.yaml).

**Comment by shermansiu** [comment]
This is not a question, I'm just trying to copy #10.

**Comment by shermansiu** [comment]
@conda-forge-admin, please re-render

**Comment by shermansiu** [comment]
@jakirkham Wait... How is this supposed to work?

**Comment by jakirkham** [comment]
Thanks for reaching out Sherman! 🙏 Also Happy New Year! 🥳

<hr>

The updates are a bit more involved than re-rendering the `cuda-version` package

There are several feedstocks that need updates. Though `cuda-version` is certainly one of those

At the moment we are still finishing up CUDA 12.2, so this will come after that is done ( https://github.com/conda-forge/cuda-feedstock/issues/13 )

To track CUDA 12.3.1, have filed issue ( https://github.com/conda-forge/cuda-feedstock/issues/15 )

Going to close to consolidate
