### ISSUE TITLE
`cuda-version` is currently not usable

### ISSUE THREAD

**Issue by leofang** [conda-forge/cuda-version-feedstock#7]
Consider this simple case
```
$ conda create -y bbbbbb
$ conda activate bbbbbb
$ mamba install nccl "cuda-version=10.2.*"

...

Could not solve for environment specs
The following packages are incompatible
├─ cuda-version 10.2**  is installable and it requires
│  └─ cudatoolkit 10.2 , which can be installed;
└─ nccl   is uninstallable because there are no viable options
   ├─ nccl [2.4.6.1|2.4.7.1|...|2.8.4.1] would require
   │  └─ cudatoolkit 9.2|9.2.* , which conflicts with any installable versions previously reported;
   ├─ nccl [2.10.3.1|2.11.4.1|...|2.9.9.1] would require
   │  └─ cudatoolkit 10.2|10.2.* , which conflicts with any installable versions previously reported;
   ├─ nccl [2.10.3.1|2.11.4.1|...|2.9.9.1] would require
   │  └─ cudatoolkit 10.0|10.0.* , which conflicts with any installable versions previously reported;
   ├─ nccl [2.10.3.1|2.11.4.1|...|2.9.9.1] would require
   │  └─ cudatoolkit 10.1|10.1.* , which conflicts with any installable versions previously reported;
   ├─ nccl [2.10.3.1|2.11.4.1|...|2.9.9.1] would require
   │  └─ cudatoolkit 11.0|11.0.* , which conflicts with any installable versions previously reported;
   ├─ nccl [2.10.3.1|2.11.4.1|...|2.9.9.1] would require
   │  └─ cudatoolkit 11.1|11.1.* , which conflicts with any installable versions previously reported;
   └─ nccl [2.10.3.1|2.11.4.1|...|2.9.9.1] would require
      └─ cudatoolkit [>=11.2,<12 |>=11.2,<12.0a0 ], which conflicts with any installable versions previously reported.
```
As soon as `cuda-version` is added for the solver to consider, we always hit an unresolved error. I think the reason is the same as [this](https://github.com/conda-forge/ucx-split-feedstock/issues/120): When [patching the repodata](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/435/files), it should be 
```
cudatoolkit X.Y | X.Y.*
```
not just 
```
cudatoolkit X.Y
```
I'll send a patch to fix it, similar to [John's fix earlier today](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/445).

cc: @conda-forge/cuda-version

**Comment by jakirkham** [comment]
Is this still an issue if we do (so dropping `.*`)?

```
mamba install nccl "cuda-version=10.2"
```

**Comment by leofang** [comment]
yea

**Comment by jakirkham** [comment]
Ok thanks Leo! 🙏

Agree that sounds like the issue

Would you like to start a PR in this feedstock? Would be happy to review

**Comment by leofang** [comment]
np @jakirkham I sent #8

**Comment by jakirkham** [comment]
Thanks Leo! 🙏

Next step will be to fix the repodata patch. This will involve 2 parts:
* Update patch applied on old versions ( just like PR #8 )
* Patch more recent packages to relax constraint ( analogous to PR https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/445 )

**Comment by leofang** [comment]
yes on it

**Comment by leofang** [comment]
Sent https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/447.

**Comment by jakirkham** [comment]
Thanks Leo! 🙏

That's now merged
