### ISSUE TITLE
Packages in `nvidia` channel do not depend on `cuda-version`

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/cuda-version-feedstock#9]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

All of the cuda packages in the `nvidia` channel do not depend on the `cuda-version` package, so if you have both `nvidia` and `conda-forge` channels in your conda config then the packages in the `nvidia` channel can get installed in a version not aligned to `cuda-version`.

I.E. https://anaconda.org/nvidia/cuda-cudart/files/modal/info/64c7f1ba52b7408c0c8a7792

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jakirkham** [comment]
Sorry you ran into this Keith. Yep this is a known issue

We need to upstream changes from the `conda-forge` packages to the `nvidia` packages (this is just one example of that)

cc @adibbley

**Comment by jakirkham** [comment]
This is now fixed starting with CUDA 12.5.0
